### PR TITLE
Squashed a few bugs. Closes #70 & #141 & #60 & #146

### LINKED ISSUE #70: Ptah's Decadence drops an extra Diamond in addition to an Ore block with Silk Touch. (Causing infinite Diamond loop.)

### PR DESCRIPTION
**Pull request by GirafiStudios**

### CODE REVIEW

File: src/main/java/com/teammetallurgy/atum/blocks/AtumBlocks.java [hunk 1]
```diff
@@ -119,8 +119,8 @@ public void registerBlocks() {
         GameRegistry.registerBlock(BLOCK_THINCRYSTALSTAINEDGLASS, ItemBlockStainedGlass.class, BLOCK_THINCRYSTALSTAINEDGLASS.getUnlocalizedName());
         GameRegistry.registerBlock(BLOCK_THINFRAMEDSTAINEDGLASS, ItemBlockStainedGlass.class, BLOCK_THINFRAMEDSTAINEDGLASS.getUnlocalizedName());
 
-        GameRegistry.registerBlock(BLOCK_SLABS, ItemBlockSlab.class, BLOCK_SLABS.getUnlocalizedName());
-        GameRegistry.registerBlock(BLOCK_DOUBLESLAB, ItemBlockSlab.class, BLOCK_DOUBLESLAB.getUnlocalizedName());
+        GameRegistry.registerBlock(BLOCK_SLABS, ItemBlockSlab.class, "slab");
+        GameRegistry.registerBlock(BLOCK_DOUBLESLAB, ItemBlockSlab.class, "doubleSlab");
```
Comment (Glassmaker) [inline src/main/java/com/teammetallurgy/atum/blocks/AtumBlocks.java]: Kindly revert these, as it removes blocks from current worlds.

File: src/main/java/com/teammetallurgy/atum/blocks/ItemBlockSlab.java [hunk 2]
```diff
@@ -1,27 +1,27 @@
...
 
-public class ItemBlockSlab extends ItemBlock {
-    public static final String[] types = {"smooth", "cracked", "largeBrick", "smallBrick"};
+import java.util.List;
 
-    public ItemBlockSlab(Block block) {
-        super(block);
-        setHasSubtypes(true);
+public class ItemBlockSlab extends ItemSlab {
+    public static final String[] slabType = {"smooth", "cracked", "largeBrick", "smallBrick"};
```
Comment (Glassmaker) [inline src/main/java/com/teammetallurgy/atum/blocks/ItemBlockSlab.java]: Unnecessary variable name change, kindly revert to types

File: src/main/java/com/teammetallurgy/atum/blocks/AtumBlocks.java (hunk 1 above)
Comment (GirafiStudios) [inline src/main/java/com/teammetallurgy/atum/blocks/AtumBlocks.java]: No it does not. I'm using the same names, that there was set before. I just can't use setBlockName() anymore, because the slabs have to be a BlockSlab, which is an abstract class.

Comment (Glassmaker) [inline src/main/java/com/teammetallurgy/atum/blocks/AtumBlocks.java]: when you use getUnlocalizedName it returns tile.BlockName, you removed the "tile.", so the ID changes and removes blocks

**Comment by Glassmaker** [comment]
Thanks for more fixes :)
